data:
  width: 512
  height: 384
  n_sample_frames: 8
num_inference_steps: 30
decode_chunk_size: 8
overlap: 4
noise_aug_strength: 0.1
min_appearance_guidance_scale: 2
max_appearance_guidance_scale: 2
i2i_noise_strength: 1
weight_dtype: fp16
pretrained_model_name_or_path: models/stable-video-diffusion-img2vid-xt
unet_checkpoint_path: models/face_restoration/unet.pth
id_linear_checkpoint_path: models/face_restoration/id_linear.pth
net_arcface_checkpoint_path: models/face_restoration/insightface_glint360k.pth
